# Site
title:              Denny Sam
bio:                'Creative individual with many pasions, but learning, problem solving and working on innovative ideas dominate the list. Worked with over 15 frameworks and languages. Curently working with frameworks like ReactJS along with doing UI/UX research. Interested in getting into research and analysis of inteligent systems'
description:        "Creative individual with many pasions, but learning, problem solving and working on innovative ideas dominate the list. Worked with over 15 frameworks and languages. Curently working with frameworks like ReactJS along with doing UI/UX research. Interested in getting into research and analysis of inteligent systems"
reading_time:       false
words_per_minute:   200
logo:               'assets/img/logo.png'
background:         'assets/img/bg.png'
tiled_bg:           true   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://itsdennian.github.io/

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   dennysam

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
#email:
github-url:         itsdennian
twitter:            itsdennian
facebook:           itsdennian
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#xing:              username
# instagram:          dennysam_
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
